# Generated by Django 5.1.1 on 2024-10-04 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=100, unique=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(max_length=10)),
                ('patient_age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=255)),
                ('center', models.CharField(max_length=255)),
                ('visit_date', models.DateField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('ip_advised', models.BooleanField(default=False)),
                ('medications', models.TextField(blank=True, null=True)),
                ('investigations', models.TextField(blank=True, null=True)),
                ('diagnosis_advised', models.TextField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=255)),
                ('test_value', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to='patients.patient')),
            ],
        ),
    ]
